Repository squizlabs/PHP_CodeSniffer, pull requests merged in 2023-05, with the labels that each got.

#3722 Potential "Uninitialized string offset 1" in octal notation backfill
  src/Tokenizers/PHP.php
  tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.inc
  tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
Labels: Bug

#3797 Tokenizer/PHP: more context sensitive keyword fixes
  src/Tokenizers/PHP.php
  tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
  tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
Labels: Bug

#3777 Squiz/NonExecutableCode: slew of bug fixes, mostly related to modern PHP
  src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
  src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.1.inc
  src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.php
Labels: Bug

#3779 Squiz/LowercasePHPFunctions + Generic/ForbiddenFunctions: bug fix for class names in attributes
  src/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
  src/Standards/Generic/Tests/PHP/ForbiddenFunctionsUnitTest.inc
  src/Standards/Squiz/Sniffs/PHP/LowercasePHPFunctionsSniff.php
  src/Standards/Squiz/Tests/PHP/DiscouragedFunctionsUnitTest.inc
  src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc
  src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc.fixed
Labels: Bug

#3787 PEAR/Squiz/[MultiLine]FunctionDeclaration: allow for PHP 8.1 new in initializers
  src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
  src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc
  src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc.fixed
  src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc
  src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc.fixed
Labels: Bug

#3637 PHP 8.1 | PSR2/PropertyDeclaration: add check for visibility before readonly keyword
  src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
  src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
  src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
  src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
Labels: Type: enhancement, Standard: PSR2, Focus: Modern PHP

#3761 PHP 8.1 | Config: fix passing null to non-nullable notice
  src/Config.php
Labels: Type: bug, Core Component: Config & Ruleset & CLI options

#3823 Add a pull request template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Type: chores/QA, Type: meta

#3824 Bug report template: add notice about external standards
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Type: chores/QA, Type: meta

#3629 PHP 8.2 | Ruleset: prevent notices about dynamic properties being set
  package.xml
  phpcs.xml.dist
  scripts/ValidatePEAR/ValidatePEARPackageXML.php
  src/Files/File.php
  src/Ruleset.php
  tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedAsDeclaredSniff.php
  tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedViaMagicMethodSniff.php
  tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedViaStdClassSniff.php
  tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyNotAllowedViaAttributeSniff.php
  tests/Core/Ruleset/RuleInclusionTest.php
  tests/Core/Ruleset/RuleInclusionTest.xml
  tests/Core/Ruleset/SetPropertyAllowedAsDeclaredTest.xml
  tests/Core/Ruleset/SetPropertyAllowedViaMagicMethodTest.xml
  tests/Core/Ruleset/SetPropertyAllowedViaStdClassTest.xml
  tests/Core/Ruleset/SetPropertyAppliesPropertyToMultipleSniffsInCategoryTest.xml
  tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForCategoryTest.xml
  tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForStandardTest.xml
  tests/Core/Ruleset/SetPropertyNotAllowedViaAttributeTest.xml
  tests/Core/Ruleset/SetPropertyThrowsErrorOnInvalidPropertyTest.xml
  tests/Core/Ruleset/SetSniffPropertyTest.php
Labels: Type: bug, Core Component: Config & Ruleset & CLI options

#3820 Config: add tests for the `reportWidth` setting
  package.xml
  tests/Core/Config/ReportWidthTest.php
Labels: Type: chores/QA, Core Component: Config & Ruleset & CLI options

#3825 GH Actions: automate some label management
  .github/workflows/manage-labels.yml
Labels: Type: chores/QA

#3801 File::getMethodParameters(): allow for readonly promoted properties without visibility
  src/Files/File.php
  tests/Core/File/GetMethodParametersTest.inc
  tests/Core/File/GetMethodParametersTest.php
Labels: Type: bug, Core Component: File, Focus: Modern PHP

#3686 PHP 8.2 | File::getClassProperties(): add support for readonly classes
  package.xml
  src/Files/File.php
  tests/Core/File/GetClassPropertiesTest.inc
  tests/Core/File/GetClassPropertiesTest.php
Labels: Type: enhancement, Core Component: File, Focus: Modern PHP

#3728 PHP 8.2 | PSR1/SideEffects: allow for readonly classes
  src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
  src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.1.inc
Labels: Type: bug, Standard: PSR1, Focus: Modern PHP

#3816 PSR12/FileHeader: bug fix - false positives on PHP 8.2+ readonly classes
  package.xml
  src/Standards/PSR12/Sniffs/Files/FileHeaderSniff.php
  src/Standards/PSR12/Tests/Files/FileHeaderUnitTest.18.inc
Labels: Type: bug, Standard: PSR12, Focus: Modern PHP

#3837 Reduce width of table in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Type: chores/QA, Type: meta
